apiVersion: apps/v1
kind: Deployment
metadata:
  name: schonk-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schon-klinik-app
  template:
    metadata:
      labels:
        app: schon-klinik-app
    spec:
      containers:
      - name: klinikContainer
        image: klinikacr1.azurecr.io/app:scklinik
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: schon-klinik-app-svc
spec:
  selector:
    app: schon-klinik-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
