# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger
- master

pool:
  name: Azure Pipelines
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Azure subscription 1 (e6ef4365-1933-400b-b14b-23c21484392e)'
    azureContainerRegistry: '{"loginServer":"klinikacr1.azurecr.io", "id" : "/subscriptions/e6ef4365-1933-400b-b14b-23c21484392e/resourceGroups/klinik-rg/providers/Microsoft.ContainerRegistry/registries/klinikacr1"}'
    imageName: '$(Build.Repository.Name):scklinik'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Azure subscription 1 (e6ef4365-1933-400b-b14b-23c21484392e)'
    azureContainerRegistry: '{"loginServer":"klinikacr1.azurecr.io", "id" : "/subscriptions/e6ef4365-1933-400b-b14b-23c21484392e/resourceGroups/klinik-rg/providers/Microsoft.ContainerRegistry/registries/klinikacr1"}'
    action: 'Push an image'
    imageName: '$(Build.Repository.Name):scklinik'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: 'azure-aks.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
